/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package discoveryProject;

import org.junit.Test;
import org.junit.runner.RunWith;

import DiscoveryProject.Library;
import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

import static org.junit.Assert.*;
@RunWith(Cucumber.class)
@CucumberOptions(monochrome = false, dryRun =false,
features = { "src/test/resources/Discovery.feature" }, 

glue = { "gluecodes" },

tags = { "@smoke" },

plugin={"pretty", "html:target/cucumber"})


public class discoveryrunner {
    @Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
